apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "myquarkus"
  description: "myquarkus"
  tags:
    - java
    - quarkus
  links:
    - url: https://eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/myquarkus?devfilePath=.devfilev2-theia.yaml
      title: CodeReady Workspaces (Eclipse Theia)
      icon: web
    - url: https://eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/myquarkus?che-editor=che-incubator/che-code/insiders&devfilePath=.devfilev2-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web    
    - url: https://eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/myquarkus?che-editor=che-incubator/che-idea/next&devfilePath=.devfilev2-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
    - url: https://grafana-route-user-workload-grafana.apps.control-cluster-raffa.demo.red-chesterfield.com/d/AqEG4weWk/error-budget?orgId=1&refresh=5s&var-virtual_service=myquarkus.myapp-prod.svc.cluster.local&var-time_interval=1h&var-SLO=95&var-latency=1000
      title: SRE Metrics (production)
      icon: web
  annotations:
    'github.com/project-slug': raf-backstage-demo/myquarkus
    'backstage.io/kubernetes-id': myquarkus
    'backstage.io/techdocs-ref': dir:.
    'sonarqube.org/project-key': raf-backstage-demo_myquarkus
    'prometheus.io/alert': ErrorBudgetBurn-critical-myapp-prod-myquarkus,ErrorBudgetBurn-warning-myapp-prod-myquarkus
    'prometheus.io/rule': virtual_service:myapp_prod_myquarkus:error_rate_1d,virtual_service:myapp_prod_myquarkus:error_rate_1h,virtual_service:myapp_prod_myquarkus:error_rate_2h,virtual_service:myapp_prod_myquarkus:error_rate_30m
spec:
  type: service
  lifecycle: experimental
  owner: "demo-team-a"
  system: system:myapp